openapi: 3.2.0
info:
  title: Portal Computer Checkin API
  version: v1.0.0
security:
- Authorization: []
  ManagedOrganizationId: []
  OverrideManagedOrganizationId: []
tags:
- name: ComputerCheckin
paths:
  /portalapi/ComputerCheckin/ComputerCheckinGetByParameters:
    post:
      tags:
      - ComputerCheckin
      summary: Get Computer Check-In History by Parameters
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ComputerCheckinParametersDto'
          text/json:
            schema:
              $ref: '#/components/schemas/ComputerCheckinParametersDto'
          application/*+json:
            schema:
              $ref: '#/components/schemas/ComputerCheckinParametersDto'
      responses:
        '200':
          description: OK
components:
  schemas:
    ComputerCheckinParametersDto:
      type: object
      properties:
        computerId:
          type: string
          format: uuid
        pageSize:
          type: integer
          format: int32
        pageNumber:
          type: integer
          format: int32
        hideHeartbeat:
          type: boolean
        showTotalCount:
          type: boolean
      additionalProperties: false
  securitySchemes:
    Authorization:
      type: apiKey
      description: Please insert Standard Authorization header.
      name: Authorization
      in: header
    ManagedOrganizationId:
      type: apiKey
      description: Please insert Managed Organization Id.
      name: ManagedOrganizationId
      in: header
    OverrideManagedOrganizationId:
      type: apiKey
      description: Please insert Managed Organization Id.
      name: OverrideManagedOrganizationId
      in: header
