openapi: 3.2.0
info:
  title: Portal Report API
  version: v1.0.0
security:
- Authorization: []
  ManagedOrganizationId: []
  OverrideManagedOrganizationId: []
tags:
- name: Report
paths:
  /portalapi/Report/ReportGetByOrganizationId:
    get:
      tags:
      - Report
      summary: Get report(s) by organization id.
      responses:
        '200':
          description: OK
  /portalapi/Report/ReportGetDynamicData:
    post:
      tags:
      - Report
      summary: Generate report data.
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ReportParams'
          text/json:
            schema:
              $ref: '#/components/schemas/ReportParams'
          application/*+json:
            schema:
              $ref: '#/components/schemas/ReportParams'
      responses:
        '200':
          description: OK
components:
  schemas:
    ReportParams:
      type: object
      properties:
        reportId:
          type: string
          format: uuid
          default: 00000000-0000-0000-0000-000000000000
        startDate:
          type: string
          format: date-time
          default: null
        endDate:
          type: string
          format: date-time
          default: null
        data:
          type:
          - string
          - 'null'
          default: ''
        offsetInMinutes:
          type: integer
          format: int32
        id:
          type: string
          format: uuid
          default: 00000000-0000-0000-0000-000000000000
        includeChildOrganizations:
          type: boolean
        options:
          type:
          - array
          - 'null'
          items:
            $ref: '#/components/schemas/ReportParamsOption'
      additionalProperties: false
    ReportParamsOption:
      type: object
      properties:
        name:
          type:
          - string
          - 'null'
        value: {}
      additionalProperties: false
  securitySchemes:
    Authorization:
      type: apiKey
      description: Please insert Standard Authorization header.
      name: Authorization
      in: header
    ManagedOrganizationId:
      type: apiKey
      description: Please insert Managed Organization Id.
      name: ManagedOrganizationId
      in: header
    OverrideManagedOrganizationId:
      type: apiKey
      description: Please insert Managed Organization Id.
      name: OverrideManagedOrganizationId
      in: header
